name: tbib_file_uploader
description: Upload image or file widget and will receive file name and path
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  dio: ^5.3.0
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  permission_handler: ^10.4.3

dev_dependencies:
  mocktail: ^0.3.0
  svg_to_font: ^1.0.2
  test: ^1.19.2
  very_good_analysis: ^5.0.0

flutter:
  fonts:
    - family: tbibIcons
      fonts:
        - asset: assets/fonts/tbib_icons.ttf
